name: API Sample Build

on:
  push:
    branches:
      - develop
      - release
      - master
    paths:
      - api-sample/**
      - core/**
      - domain-sample/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew api-sample:build

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew jacocoRootReport coveralls